# Generated by Django 5.2.8 on 2025-11-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True  # 紀錄是不是第一個Migration

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",  # 資料表名稱
            fields=[  # 欄位
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),  # Django自動新增的欄位,因為原本的Class沒有PK
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
